repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-non-slow
        name: pytest (no slow tests)
        entry: pytest -v -m "not slow"
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]

      - id: pytest-all-periodic
        name: pytest (all tests, every 5 pushes)
        entry: python scripts/run_periodic_tests.py
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]
